### ISSUE TITLE
Sugestao de melhoria

### ISSUE THREAD

**Issue by rvalins** [othiagobruno/validatorless#12]
Hoje com um campo númerico, por exemplo, quando o utilizador deve informar um valor, ao usar o validator como;
  validator: Validatorless.multiple([
                Validatorless.required('Campo obrigatório'),
                Validatorless.min(1, 'Valor precisa ter pelo menos 1 dígito')
                
           O utilizador consegue incluir o valor como "0". (Afinal tem um digito, o que faz com que as duas validações sejam verdadeiras. Sugiro então uma implementação que valide o range numérico, exemplo: valor min, valor max, entre valores. Não obstante, muito obrigado por este excelente pacote

**Comment by othiagobruno** [comment]
Muito boa a sugestão! Hoje temos essa funcionalidade: Validatorless.between(1, 3, 'Valor entre 1 e 3')

**Comment by rvalins** [comment]
perfeito, Thiago, fico feliz por contribuir. Pena nao ter o conhecimento suficiente para trazer a solução. Apenas um pormenor que gostaria de adicionar: no caso, o between para mim nao funcionou porque o campo seria de "valor monetario" (string), isto é, talvez a funcao deveria fazer um strip de forma a desconsiderar os elementos de moeda (como R$, por exemplo)

**Comment by othiagobruno** [comment]
@rvalins O Rodrigo Rahman fez um video explicando como estender o package para novas funções validadores. 

caso queira acompanhar, segue o link:
https://www.youtube.com/watch?v=kfoVcHJq8lk&t=200s
